apiVersion: v2
name: ts-server-boilerplate
description: A Helm chart for ts-server-boilerplate service
type: application
version: 0.1.5
appVersion: 0.1.5
dependencies:
  - name: common
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: 1.0.0
