name: pull_request

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  eslint:
    name: Run TS Project eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24.x]

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v7

      - name: Init Nodejs
        uses: MapColonies/shared-workflows/actions/init-npm@init-npm-v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run TS Project linters
        uses: wearerequired/lint-action@v3
        with:
          eslint: true
          prettier: true
          eslint_extensions: ts
          tsc: true

  openapi-lint:
    name: Run OpenAPI lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v7

      - name: Init Nodejs
        uses: MapColonies/shared-workflows/actions/init-npm@init-npm-v1

      - name: OpenAPI Lint Checks
        run: npx @redocly/cli lint --format=github-actions openapi3.yaml

  helm-lint:
    name: Run Helm lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Helm Lint Checks
        uses: MapColonies/shared-workflows/actions/helm-lint@helm-lint-v1

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [24.x]

    container:
      image: node:${{ matrix.node }}

    services:
      elasticsearch:
        image: elasticsearch:8.13.0
        env:
          discovery.type: single-node
          xpack.security.enabled: false
          xpack.security.enrollment.enabled: false
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Init Nodejs
        uses: MapColonies/shared-workflows/actions/init-npm@init-npm-v1
        with:
          node-version: ${{ matrix.node }}

      - name: Wait for Elasticsearch
        run: |
          until curl -s http://elasticsearch:9200/_cluster/health | grep '"status":"green"'; do
            echo "Waiting for Elasticsearch...";
            sleep 5;
          done

      - name: Run tests
        run: npm run test

      - uses: actions/upload-artifact@v7
        with:
          name: Test Reporters Node-${{ matrix.node }}
          path: reports/**

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker image
        uses: docker/build-push-action@v7
